# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: zh

pipeline:
  # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
  # # If you'd like to customize it, uncomment and adjust the pipeline.
  # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: compoments.nlu.tokenizers.bert_tokenizer.CustomBertTokenizer
    cache_dir: /Volumes/Work/NLP_Learning/RASA_DialogueSystem/rasa_ch_faq/tmp
    model_weights: /Volumes/Work/NLP_Learning/RASA_DialogueSystem/rasa_ch_faq/pre_models
  - name: LanguageModelFeaturizer
    cache_dir: /Volumes/Work/NLP_Learning/RASA_DialogueSystem/rasa_ch_faq/tmp
    model_name: bert
    model_weights: /Volumes/Work/NLP_Learning/RASA_DialogueSystem/rasa_ch_faq/pre_models
  - name: DIETClassifier
    epochs: 100
  - name: RegexEntityExtractor
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: rasa_faq
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: AugmentedMemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
    core_fallback_threshold: 0.4
    enable_fallback_prediction: True
    core_fallback_action_name: "action_default_fallback"
  # - name: compoments.polices.ask_again_policy.AskAgainRulePolicy
  #   core_fallback_threshold: 0.5
  #   ask_again_intent: "再问一次"
  #   need_ask_again_intents:
  #     - "request_weather"

